### ISSUE TITLE
Fix incomplete scene copies after export

### ISSUE THREAD

**Issue by JonasT** [09th/YABEE#1]
"- Incomplete scene clearing. Whenever we are deleted our temporary scene,
Blender won't to delete other objects, created with the scene, so
we should do it by hand. I recommend to save the .blend file before
exporting and reload it after."

Please fix! Very unintuitive, and I never noticed and now that I checked, I have a lot of scenes but no idea which one was the original one, I can only guess. That is quite bad, what if I mess something up trying to fix this again. The exporter really shouldn't leave such a chaos after exporting!!

**Comment by 09th** [comment]
Fixed in 2b8cd511665e503b0e00dfe988e12da6d411a22d
