### ISSUE TITLE
Import an animation from blender 2.74 deforms the model

### ISSUE THREAD

**Issue by TurBoss** [09th/YABEE#16]
Hi,
I'm trying to play an animation exported from blender ussing YABEE I'm on blender 2.74,
The actor loads ok but when i play the animation the model is deformed

![bug](https://cloud.githubusercontent.com/assets/184088/8026411/92346444-0d74-11e5-926c-bd8560af2c42.jpg)

Model.blend
https://mega.co.nz/#!kEgikRxB!CpXRjFL8CgNhO-TmpR7GyNs9x8eyuudc0MKgdzgD6sA

Model.egg
https://mega.co.nz/#!wUwWmKoS!0CMHFLMCR8J58PnKlYAJEqAnkjsMASYtWHa4JVUy6vw

Animation.egg
https://mega.co.nz/#!JVoEXZZa!blL0LiU3aXF0J5JbXH6tdg4PsLMPfWILwDzsqZPagHM

**Comment by 09th** [comment]
Fix pushed. Check it plz.

**Comment by TurBoss** [comment]
It worked :D thanks!
