### ISSUE TITLE
Space character in shape key name breaks export

### ISSUE THREAD

**Issue by JonasT** [09th/YABEE#2]
Space characters in shape key names break the export (while blender seems to consider them perfectly valid) - at least if the instant preview is enabled since the panda previewer will fail to load the model again due to a syntax error in the egg file.

The exporter should either figure out how to embed space characters in shape key names properly, or if really not possible then at least display a verbose error with instructions to change the shape key name and abort cleanly.

**Comment by 09th** [comment]
Fixed by someone, as i see
