### ISSUE TITLE
YABEE does not export scale animations on Blender 2.76

### ISSUE THREAD

**Issue by hrnf** [09th/YABEE#22]
I have tried with multiple models (as simple as a cube with two bones) and downloading yabee again from github, but it seems yabee can't recognize scales in animations.

Is this a bug or an unsupported feature?.

**Comment by 09th** [comment]
No one asked this feature before, so it's not supported, but I think it not a big problem to add it. I'll see what I can do.

**Comment by 09th** [comment]
Ok, I made changes, pls, try with new version

**Comment by hrnf** [comment]
Ok. I downloaded it and it works. Thank you very much for your work!.
