### ISSUE TITLE
Split normals not supported

### ISSUE THREAD

**Issue by JonasT** [09th/YABEE#3]
YABEE doesn't support a feature which I was told in the blender chat is named "split normals".

To test, put up a sphere and then select all edges and set them to smooth, then pick a single pair of connected edges and set to sharp, then enable Object Data > Normals > Auto Smoothing. Sadly, this result won't be exported properly unless you use an edge split modifier - however, that is impossible for export when any shape keys are in the model due to blender limitations I don't understand.

**Comment by 09th** [comment]
Partially fixed. If I understand correctly, full support is not possible. It depends from the internal Blender "Autosmooth" mechanism, which not realised in Panda.
