### ISSUE TITLE
Export doesn't work (master from a few hours ago)

### ISSUE THREAD

**Issue by JonasT** [09th/YABEE#5]
I just tried exporting this thing: http://www.homeofjones.de/temp/girlbaked.blend

However, I'm getting this backtrace:

Objects for export: ['Armature']
WRITE main EGG to /home/jonas/Develop/shadowgirl/gfx/girlbaked.egg
Traceback (most recent call last):
  File "/home/jonas/.config/blender/2.73/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 1411, in write_out
    file.write(ac.get_full_egg_str())
  File "/home/jonas/.config/blender/2.73/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 1069, in get_full_egg_str
    for line in self.get_skeleton_anim_str(obj_name).splitlines():
  File "/home/jonas/.config/blender/2.73/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 1047, in get_skeleton_anim_str
    for line in self.bone_groups[obj_name].get_full_egg_str(data, self.framerate, -1).splitlines():
  File "/home/jonas/.config/blender/2.73/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 917, in get_full_egg_str
    egg_str += ch.get_full_egg_str(anim_info, framerate, level + 1)
  File "/home/jonas/.config/blender/2.73/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 892, in get_full_egg_str
    bone_data = anim_info['<skeleton>'][self.object.yabee_name]
KeyError: 'root'

**Comment by 09th** [comment]
Fix pushed. Try to export model with this fix. Also - it's not good idea to use fiew animations in one file with model in my opinion.

**Comment by JonasT** [comment]
I think this is was actually a user error on my side: the "To" frame number appears to be exclusive, not inclusive.

However, maybe the interface should communicate it better and obviously, From: 1 To: 1 is invalid with an exclusive "To" number and there should probably be some more helpful error message when that happens other than a random backtrace + generic error.

**Comment by 09th** [comment]
I just make silent adding +1 to the "To frame" if from==to. Also I added workaround for case when mesh not parented to armature as in your model.

**Comment by JonasT** [comment]
Yes but now you're allowing an inclusive "To frame" number for the special case from==to, but otherwise requiring exclusive "To frame" numbers. How does that make any sense?

**Comment by JonasT** [comment]
I would rather propose the following:

1. from==to should fail, but it should give me a proper error message, e.g. "Your animation named <blubb> has zero frames which is invalid. Please keep in mind that To frame numbers are exclusive."
2. Add a tooltip to the "To" field which says "Frame to which animation extends (exclusive)"

**Comment by 09th** [comment]
Ok. I've added warning message, but kept adding frame as workaround.
-------------
Animation "%s" has the same "from" and "to" frames.
Keep in mind that "To frame" value is exclusive.
It means that in this case your animation contains zero of frames. YABEE will automatically add one frame to the "to frame" value of "%s" animation.

**Comment by JonasT** [comment]
That sounds like a good solution, thanks!
